#define XCPKG_VERSION_STRING "0.30.0"
#define XCPKG_VERSION_MAJOR  0
#define XCPKG_VERSION_MINOR  30
#define XCPKG_VERSION_PATCH  0

#define XCPKG_BUILD_TIMESTAMP "@COMPILED_TIMESTAMP@"

#define XCPKG_HELP "@XCPKG_HELP@"
#define XCPKG_ZSH_COMPLETION "@XCPKG_ZSH_COMPLETION@"
#define XCPKG_URL_TRANSFORM_SAMPLE "@XCPKG_URL_TRANSFORM_SAMPLE@"
