#define XCPKG_VERSION_STRING "0.30.0"
#define XCPKG_VERSION_MAJOR  0
#define XCPKG_VERSION_MINOR  30
#define XCPKG_VERSION_PATCH  0

#define XCPKG_BUILD_TIMESTAMP "@COMPILED_TIMESTAMP@"

#define XCPKG_HELP "@XCPKG_HELP@"
#define XCPKG_ZSH_COMPLETION "@XCPKG_ZSH_COMPLETION@"
#define XCPKG_URL_TRANSFORM_SAMPLE "@XCPKG_URL_TRANSFORM_SAMPLE@"
#define XCPKG_INSTALL "@XCPKG_INSTALL@"

#define XCPKG_WRAPPER_NATIVE_CC   "@XCPKG_WRAPPER_NATIVE_CC@"
#define XCPKG_WRAPPER_NATIVE_CXX  "@XCPKG_WRAPPER_NATIVE_CXX@"
#define XCPKG_WRAPPER_NATIVE_OBJC "@XCPKG_WRAPPER_NATIVE_OBJC@"

#define XCPKG_WRAPPER_TARGET_CC   "@XCPKG_WRAPPER_TARGET_CC@"
#define XCPKG_WRAPPER_TARGET_CXX  "@XCPKG_WRAPPER_TARGET_CXX@"
#define XCPKG_WRAPPER_TARGET_OBJC "@XCPKG_WRAPPER_TARGET_OBJC@"
