name: publish xcpkg main

on:
  workflow_dispatch:

jobs:

  base:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id:  calculate-release-version
        run: |
          RELEASE_VERSION=$(sed -n '/project(xcpkg VERSION /p' c/CMakeLists.txt | sed 's|project(xcpkg VERSION \([0-9.]*\) .*)|\1|')
          printf 'RELEASE_VERSION=%s\n' "$RELEASE_VERSION" >> "$GITHUB_OUTPUT"

    outputs:
      release-version: ${{ steps.calculate-release-version.outputs.RELEASE_VERSION }}


  build:
    needs: base

    runs-on: macos-15

    strategy:
      fail-fast: false
      matrix:
        target-version: ['10.15', '11.0', '12.0', '13.0', '14.0', '15.0']
        target-arch: [x86_64, arm64]

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - run: ./ppkg setup
      - run: ./ppkg update
      - run: ./ppkg install macos-${{ matrix.target-version }}-${{ matrix.target-arch }}/xcpkg
      - run: ./ppkg bundle  macos-${{ matrix.target-version }}-${{ matrix.target-arch }}/xcpkg .tar.xz

      - uses: actions/upload-artifact@v4
        with:
          name: xcpkg-${{ needs.base.outputs.release-version }}-macos-${{ matrix.target-version }}-${{ matrix.target-arch }}.tar.xz
          path: ./*.tar.xz


  publish:

    needs: [base, build]

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: .
          merge-multiple: true

      - run: ls -a

      # to avaid: failed to run git: fatal: not a git repository (or any of the parent directories): .git
      - run: git -c init.defaultBranch=master init
      - run: git remote add origin ${{ github.repositoryUrl }}

      - run: gh release create ${{ needs.base.outputs.release-version }} *.tar.xz --title ${{ needs.base.outputs.release-version }} --notes ' '
