name: publish

on:
  workflow_dispatch:
    #schedule:
    #- cron: '0 1 * * *'

jobs:
  publish:

    runs-on: macos-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          RELEASE_VERSION="$(./xcpkg --version)"

          install -d "xcpkg-$RELEASE_VERSION/bin/"
          install -d "xcpkg-$RELEASE_VERSION/share/zsh/vendor-completions/"

          cp xcpkg "xcpkg-$RELEASE_VERSION/bin/xcpkg"
          cp xcpkg-zsh-completion "xcpkg-$RELEASE_VERSION/share/zsh/vendor-completions/_xcpkg"

          RELEASE_FILE_NAME="xcpkg-$RELEASE_VERSION.tar.gz"

          tar zvcf "$RELEASE_FILE_NAME" "xcpkg-$RELEASE_VERSION"

          SHA256SUM="$(sha256sum "$RELEASE_FILE_NAME")"

          cat > notes.md <<EOF
          sha256sum:
          \`\`\`
          $SHA256SUM
          \`\`\`
          EOF

          gh release create "$RELEASE_VERSION" "$RELEASE_FILE_NAME" --title "$RELEASE_VERSION" --notes-file notes.md
