name: build with vcpkg

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  vcpkg:

    strategy:
      fail-fast: false
      matrix:
        version: [macos-15, macos-14, macos-13]

    runs-on: ${{ matrix.version }}

    steps:
      - run:  brew update
      - run:  brew install cmake ninja pkg-config

      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - run:  cd vcpkg && ./bootstrap-vcpkg.sh

      - run:  cd vcpkg && ./vcpkg install 'curl[http2,brotli,zstd,openssl]' libgit2 libarchive libyaml jansson sqlite3

      - run:  |
          cmake \
              -S c \
              -B build.d \
              -G Ninja \
              -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DCMAKE_INSTALL_PREFIX=./output \
              -DCMAKE_VERBOSE_MAKEFILE=ON

      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run: ./output/bin/xcpkg

      - run: ./output/bin/xcpkg --help
      - run: ./output/bin/xcpkg -h

      - run: ./output/bin/xcpkg --version
      - run: ./output/bin/xcpkg -V

      - run: ./output/bin/xcpkg util printenv

      - run: ./output/bin/xcpkg setup -v

      - run: ./output/bin/xcpkg about
      - run: ./output/bin/xcpkg about -v

      - run: ./output/bin/xcpkg integrate zsh
      - run: ./output/bin/xcpkg integrate zsh -v

      - run: ./output/bin/xcpkg formula-repo-list
      - run: ./output/bin/xcpkg formula-repo-add official-core https://github.com/leleliu008/xcpkg-formula-repository-official-core
      - run: ./output/bin/xcpkg formula-repo-list

      - run: ./output/bin/xcpkg formula-repo-add my_repo https://github.com/leleliu008/xcpkg-formula-repository-official-core
      - run: ./output/bin/xcpkg formula-repo-list
      - run: ./output/bin/xcpkg formula-repo-del my_repo
      - run: ./output/bin/xcpkg formula-repo-list

      - run: ./output/bin/xcpkg update

      - run: ./output/bin/xcpkg search lib
      - run: ./output/bin/xcpkg search zip

      - run: ./output/bin/xcpkg info-available libzip
      - run: ./output/bin/xcpkg info-available libzip --yaml
      - run: ./output/bin/xcpkg info-available libzip --json
      - run: ./output/bin/xcpkg info-available libzip summary
      - run: ./output/bin/xcpkg info-available libzip version
      - run: ./output/bin/xcpkg info-available libzip license
      - run: ./output/bin/xcpkg info-available libzip web-url
      - run: ./output/bin/xcpkg info-available libzip src-url
      - run: ./output/bin/xcpkg info-available libzip src-sha

      - run: ./output/bin/xcpkg depends libzip
      - run: ./output/bin/xcpkg depends libzip -t dot
      - run: ./output/bin/xcpkg depends libzip -t box

      - run: ./output/bin/xcpkg fetch gzip
      - run: ./output/bin/xcpkg fetch gsed -v

      - run: ./output/bin/xcpkg install libzip -v

      - run: ./output/bin/xcpkg tree libzip

      - run: ./output/bin/xcpkg info-installed libzip --prefix
      - run: ./output/bin/xcpkg info-installed libzip --files
      - run: ./output/bin/xcpkg info-available libzip --json
      - run: ./output/bin/xcpkg info-available libzip --yaml
      - run: ./output/bin/xcpkg info-installed libzip builtat
      - run: ./output/bin/xcpkg info-installed libzip builtat-iso-8601
      - run: ./output/bin/xcpkg info-installed libzip builtat-rfc-3339
      - run: ./output/bin/xcpkg info-available libzip version

      - run: ./output/bin/xcpkg bundle libzip tar.gz
      - run: ./output/bin/xcpkg bundle libzip tar.lz
      - run: ./output/bin/xcpkg bundle libzip tar.xz
      - run: ./output/bin/xcpkg bundle libzip tar.bz2
      - run: ./output/bin/xcpkg bundle libzip zip

      - run: |
          printf '%s\n' 'version: 1000' >> ~/.xcpkg/repos.d/official-core/formula/libzip.yml

      - run: ./output/bin/xcpkg ls-available
      - run: ./output/bin/xcpkg ls-installed
      - run: ./output/bin/xcpkg ls-outdated

      - run: ./output/bin/xcpkg is-available libzip
      - run: ./output/bin/xcpkg is-installed libzip
      - run: ./output/bin/xcpkg is-outdated  libzip

      - run: ./output/bin/xcpkg upgrade   libzip
      - run: ./output/bin/xcpkg reinstall libzip
      - run: ./output/bin/xcpkg uninstall libzip

      - run: ./output/bin/xcpkg formula-repo-list
      - run: ./output/bin/xcpkg formula-repo-add my_repo https://github.com/leleliu008/xcpkg-formula-repository-official-core
      - run: ./output/bin/xcpkg formula-repo-del my_repo

      - run: ./output/bin/xcpkg cleanup

      - run: ./output/bin/xcpkg upgrade-self


  vcpkg-sanitizer:

    strategy:
      fail-fast: false
      matrix:
        version: [macos-15, macos-14, macos-13]

    runs-on: ${{ matrix.version }}

    steps:
      - run:  brew update
      - run:  brew install --overwrite python@3.10 python@3.11
      - run:  brew install cmake ninja llvm pkg-config

      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - run:  cd vcpkg && ./bootstrap-vcpkg.sh

      - run:  cd vcpkg && ./vcpkg install 'curl[http2,brotli,zstd,openssl]' libgit2 libarchive libyaml jansson sqlite3

      - run:  |
          cmake \
              -S c \
              -B build.d \
              -G Ninja \
              -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DCMAKE_INSTALL_PREFIX=./output \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_C_COMPILER="$(brew --prefix llvm)/bin/clang" \
              -DCMAKE_C_FLAGS="-fsanitize=undefined -fsanitize=address -fsanitize=leak"

      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run: ./output/bin/xcpkg

      - run: ./output/bin/xcpkg --help
      - run: ./output/bin/xcpkg -h

      - run: ./output/bin/xcpkg --version
      - run: ./output/bin/xcpkg -V

      - run: ./output/bin/xcpkg setup -v

      - run: ./output/bin/xcpkg about
      - run: ./output/bin/xcpkg about -v

      - run: ./output/bin/xcpkg integrate zsh
      - run: ./output/bin/xcpkg integrate zsh -v

      - run: ./output/bin/xcpkg formula-repo-list
      - run: ./output/bin/xcpkg formula-repo-add official-core https://github.com/leleliu008/xcpkg-formula-repository-official-core
      - run: ./output/bin/xcpkg formula-repo-list

      - run: ./output/bin/xcpkg formula-repo-add my_repo https://github.com/leleliu008/xcpkg-formula-repository-official-core
      - run: ./output/bin/xcpkg formula-repo-list
      - run: ./output/bin/xcpkg formula-repo-del my_repo
      - run: ./output/bin/xcpkg formula-repo-list

      - run: ./output/bin/xcpkg update

      - run: ./output/bin/xcpkg search lib
      - run: ./output/bin/xcpkg search zip

      - run: ./output/bin/xcpkg info-available libzip
      - run: ./output/bin/xcpkg info-available libzip --yaml
      - run: ./output/bin/xcpkg info-available libzip --json
      - run: ./output/bin/xcpkg info-available libzip summary
      - run: ./output/bin/xcpkg info-available libzip version
      - run: ./output/bin/xcpkg info-available libzip license
      - run: ./output/bin/xcpkg info-available libzip web-url
      - run: ./output/bin/xcpkg info-available libzip src-url
      - run: ./output/bin/xcpkg info-available libzip src-sha

      - run: ./output/bin/xcpkg depends libzip
      - run: ./output/bin/xcpkg depends libzip -t dot
      - run: ./output/bin/xcpkg depends libzip -t box

      - run: ./output/bin/xcpkg fetch gzip
      - run: ./output/bin/xcpkg fetch gsed -v

      - run: ./output/bin/xcpkg install libzip -v

      - run: ./output/bin/xcpkg tree libzip

      - run: ./output/bin/xcpkg info-installed libzip --prefix
      - run: ./output/bin/xcpkg info-installed libzip --files
      - run: ./output/bin/xcpkg info-available libzip --json
      - run: ./output/bin/xcpkg info-available libzip --yaml
      - run: ./output/bin/xcpkg info-installed libzip builtat
      - run: ./output/bin/xcpkg info-installed libzip builtat-iso-8601
      - run: ./output/bin/xcpkg info-installed libzip builtat-rfc-3339
      - run: ./output/bin/xcpkg info-available libzip version

      - run: ./output/bin/xcpkg bundle libzip tar.gz
      - run: ./output/bin/xcpkg bundle libzip tar.lz
      - run: ./output/bin/xcpkg bundle libzip tar.xz
      - run: ./output/bin/xcpkg bundle libzip tar.bz2
      - run: ./output/bin/xcpkg bundle libzip zip

      - run: |
          printf '%s\n' 'version: 1000' >> ~/.xcpkg/repos.d/official-core/formula/libzip.yml

      - run: ./output/bin/xcpkg ls-available
      - run: ./output/bin/xcpkg ls-installed
      - run: ./output/bin/xcpkg ls-outdated

      - run: ./output/bin/xcpkg is-available libzip
      - run: ./output/bin/xcpkg is-installed libzip
      - run: ./output/bin/xcpkg is-outdated  libzip

      - run: ./output/bin/xcpkg upgrade   libzip
      - run: ./output/bin/xcpkg reinstall libzip
      - run: ./output/bin/xcpkg uninstall libzip

      - run: ./output/bin/xcpkg formula-repo-list
      - run: ./output/bin/xcpkg formula-repo-add my_repo https://github.com/leleliu008/xcpkg-formula-repository-official-core
      - run: ./output/bin/xcpkg formula-repo-del my_repo

      - run: ./output/bin/xcpkg cleanup

      - run: ./output/bin/xcpkg upgrade-self
